@startuml analysisClassDiagramUserManagement
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "User" as user

entity "UserModel" as userModel
entity "FollowUserModel" as followUserModel
entity "NotificationModel" as notificationModel

boundary "ProfileView" as profileView
boundary "EditProfileView" as editProfileView
boundary "ConfigurationView" as configurationView
boundary "ChangePasswordView" as changePasswordView
boundary "FollowersView" as followersView
boundary "FollowedView" as followedView

control "ProfileController" as profileController
control "EditProfileController" as editProfileController
control "ChangeLanguageController" as changeLanguageController
control "ChangePasswordController" as changePasswordController
control "ListUsersController" as listUsersController
control "LogoutController" as logoutController
control "FileController" as fileController
control "LogoutController" as logoutController
control "FollowUserController" as followUserController
control "NotificationsController" as notificationsController

user -- profileView
user -- editProfileView
user -- configurationView
user -- changePasswordView
user -- followersView
user -- followedView

profileView -- profileController
editProfileView -- editProfileController
editProfileView -- fileController
configurationView -- changeLanguageController
configurationView -- logoutController
changePasswordView -- changePasswordController
followersView -- listUsersController
followersView -- followUserController
followersView -- notificationsController
followedView -- listUsersController
followedView -- followUserController
profileController -- userModel
editProfileController -- userModel
changeLanguageController -- userModel
changePasswordController -- userModel
listUsersController -- userModel
logoutController -- userModel
fileController -- userModel
followUserController -- followUserModel
notificationsController -- notificationModel

@enduml