@startuml analysisClassDiagramSocialInteractions
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "User" as user

entity "UserModel" as userModel
entity "EventModel" as eventModel
entity "SocialInteractionModel" as socialInteractionModel
entity "CommentModel" as commentModel
entity "FollowUserModel" as followUserModel
entity "NotificationModel" as notificationModel

boundary "EventDetailsView" as eventDetailsView
boundary "ProfileDetailsView" as profileDetailsView
boundary "NotificationsView" as notificationsView
boundary "SearchView" as searchView

control "CommentEventController" as commentEventController
control "LikeEventController" as likeEventController
control "ShareEventController" as shareEventController
control "FollowUserController" as followUserController
control "NotificationsController" as notificationsController
control "SearchProfileController" as searchProfileController
control "EventDetailsController" as eventDetailsController
control "ProfileController" as profileController

user --> eventDetailsView
user --> profileDetailsView
user --> notificationsView
user --> searchView

eventDetailsView --> eventDetailsController
eventDetailsView --> commentEventController
eventDetailsView --> likeEventController
eventDetailsView --> shareEventController
eventDetailsView --> profileController
profileDetailsView --> followUserController
notificationsView --> notificationsController
searchView --> searchProfileController
profileDetailsView --> profileController


profileController --> userModel
eventDetailsController --> eventModel
commentEventController --> commentModel
likeEventController --> socialInteractionModel
shareEventController --> eventModel
followUserController --> followUserModel
notificationsController --> notificationModel
searchProfileController --> userModel

@enduml