@startuml analysisClassDiagramAuthentication
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11


actor "User" as user

entity "UserModel" as userModel

boundary "AuthView" as authView
boundary "ForgotPasswordView" as forgotPasswordView

control "SignUpController" as signUpController
control "LoginController" as loginController
control "ForgotPasswordController" as forgotPasswordController

user --> authView
user --> forgotPasswordView


authView --> signUpController
authView --> loginController
forgotPasswordView --> forgotPasswordController

signUpController --> userModel
loginController --> userModel
forgotPasswordController --> userModel

@enduml