@startuml analysisClassDiagramEventsManagements
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "User" as user

entity "EventModel" as eventModel

boundary "PostEventView" as postEventView
boundary "EditEventView" as editEventView
boundary "EventDetailsView" as eventDetailsView
boundary "SearchView" as searchView
boundary "ListEventsView" as listEventsView

control "PostEventController" as postEventController
control "UploadImageController" as uploadImageController
control "UploadMusicController" as uploadMusicController
control "UploadLocationController" as uploadLocationController
control "EditEventController" as editEventController
control "EditImageController" as editImageController
control "DeleteMusicController" as deleteMusicController
control "DeleteLocationController" as deleteLocationController
control "EventDetailsController" as eventDetailsController
control "SearchEventController" as searchEventController
control "ListEventsController" as listEventsController

user --> postEventView
user --> editEventView
user --> eventDetailsView
user --> searchView
user --> listEventsView

postEventView --> postEventController
postEventView --> uploadImageController
postEventView --> uploadMusicController
postEventView --> uploadLocationController
editEventView --> editEventController
editEventView --> editImageController
editEventView --> deleteMusicController
editEventView --> deleteLocationController
eventDetailsView --> eventDetailsController
searchView --> searchEventController
listEventsView --> listEventsController

postEventController --> eventModel
uploadImageController --> eventModel
uploadMusicController --> eventModel
uploadLocationController --> eventModel
editImageController --> eventModel
deleteMusicController --> eventModel
deleteLocationController --> eventModel
editEventController --> eventModel
eventDetailsController --> eventModel
searchEventController --> eventModel
listEventsController --> eventModel

@enduml