@startuml analysisClassDiagramEventsManagements
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "User" as user

entity "UserModel" as userModel
entity "EventModel" as eventModel
entity "CommentModel" as commentModel

boundary "AddEventView" as addEventView
boundary "EditEventView" as editEventView
boundary "EventDetailsView" as eventDetailsView
boundary "SearchView" as searchView
boundary "HomeView" as homeView

control "AddEventController" as addEventController
control "UploadFileController" as uploadFileController
control "UploadLocationController" as uploadLocationController
control "EditEventController" as editEventController
control "EditImageController" as editImageController
control "DeleteMusicController" as deleteMusicController
control "DeleteLocationController" as deleteLocationController
control "EventDetailsController" as eventDetailsController
control "SearchEventController" as searchEventController
control "ListEventsController" as listEventsController
control "CommentEventController" as commentEventController
control "ProfileController" as profileController

user --> addEventView
user --> editEventView
user --> eventDetailsView
user --> searchView
user --> homeView

addEventView --> addEventController
addEventView --> uploadFileController
addEventView --> uploadLocationController
editEventView --> editEventController
editEventView --> editImageController
editEventView --> deleteMusicController
editEventView --> deleteLocationController
eventDetailsView --> eventDetailsController
eventDetailsView --> commentEventController
searchView --> searchEventController
homeView --> listEventsController
homeView --> profileController
homeView --> commentEventController

addEventController --> eventModel
uploadFileController --> eventModel
uploadLocationController --> eventModel
editImageController --> eventModel
deleteMusicController --> eventModel
deleteLocationController --> eventModel
editEventController --> eventModel
eventDetailsController --> eventModel
searchEventController --> eventModel
listEventsController --> eventModel
commentEventController --> commentModel
profileController --> userModel

@enduml