@startuml analysisClassDiagramEventsManagements
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor "User" as user

entity "UserModel" as userModel
entity "EventModel" as eventModel
entity "CommentModel" as commentModel
entity "NotificationModel" as notificationModel
entity "CategoriesModel" as categoriesModel
entity "SocialInteractionModel" as socialInteractionModel
entity "LocationModel" as locationModel

boundary "AddEventView" as addEventView
boundary "EditEventView" as editEventView
boundary "EventDetailsView" as eventDetailsView
boundary "SearchView" as searchView
boundary "HomeView" as homeView


control "CategoriesController" as categoriesController
control "LikeEventController" as likeEventController
control "NotificationsController" as notificationController
control "ShareEventController" as shareEventController
control "CommentEventController" as commentEventController
control "ProfileController" as profileController
control "FileController" as fileController
control "AddEventController" as addEventController
control "LocationController" as locationController
control "EditEventController" as editEventController
control "EventDetailsController" as eventDetailsController
control "SearchEventController" as searchEventController
control "ListEventsController" as listEventsController
control "CommentEventController" as commentEventController
control "ProfileController" as profileController
control "EventDetailsController" as eventDetailsController

user --> addEventView
user --> editEventView
user --> eventDetailsView
user --> searchView
user --> homeView

addEventView --> addEventController
addEventView --> locationController
addEventView --> fileController
editEventView --> editEventController
editEventView --> eventDetailsController
editEventView --> fileController
editEventView --> locationController

eventDetailsView --> eventDetailsController
eventDetailsView --> commentEventController
eventDetailsView --> likeEventController
eventDetailsView --> profileController
eventDetailsView --> shareEventController
eventDetailsView --> notificationController
searchView --> searchEventController
searchView --> categoriesController
searchView --> likeEventController
searchView --> notificationController
searchView --> shareEventController
searchView --> profileController
searchView --> commentEventController
homeView --> listEventsController
homeView --> profileController
homeView --> commentEventController
homeView --> likeEventController
homeView --> notificationController
homeView --> shareEventController

addEventController --> eventModel
fileController --> eventModel
locationController --> locationModel
editEventController --> eventModel
eventDetailsController --> eventModel
searchEventController --> eventModel
listEventsController --> eventModel
commentEventController --> commentModel
profileController --> userModel
categoriesController --> categoriesModel
likeEventController --> socialInteractionModel
notificationController --> notificationModel

@enduml