@startuml DesignClassDiagram
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11
left to right direction
actor "Authenticated\nUser" as UserReg


package frontend <<React Native:0.76.6>>{
    boundary "AddEventView" as addEventView << TSX >>
    boundary "AddDefaultView" as AddDefaultView << TSX >>
    boundary "AddDateView" as AddDateView << TSX >>
    boundary "ChooseCategoriesView" as ChooseCategoriesView << TSX >>

    component "react" as React << Library >>
    component "useState" as useState << Hook >>
    component "useCallback" as useCallback << Hook >>

    component "@react-navigation/native" as ReactNavigation << Library >>
    component "useNavigation" as useNavigation << Hook >>
    component "useFocusEffect" as useFocusEffect << Hook >>


    component "react-native-safe-area-context" as SafeAreaContext << Library >>
    component "SafeAreaView" as SafeAreaView << Component >>

    component "react-native" as ReactNative << Library >>
    component "Image" as Image << Component >>
    component "Text" as Text << Component >>
    component "Alert" as Alert << Component >>
    component "ScrollView" as ScrollView << Component >>
    component "StyleSheet" as StyleSheet << Component >>

    component "react-i18next" as ReactI18next << Library >>
    component "useTranslation" as useTranslation << Hook >>

    component "react-native-toast-notifications" as ReactNativeToast << Library >>
    component "useToast" as useToast << Hook >>

    boundary "Modal" as Modal << Custom Components >>
    boundary "AppHeader" as AppHeader << Custom Components >>

    component "useCurrentLocation" as useCurrentLocation << Custom Hooks >>
    component "useImagePicker" as useImagePicker << Custom Hooks >>
    component "useMusicPicker" as useMusicPicker << Custom Hooks >>
    component "useAudioRecorder" as useAudioRecorder << Custom Hooks >>

    component "expo-camera" as ExpoCamera << Library >>
    component "Camera" as Camera << Component >>

    component "expo-image-picker" as ExpoImagePicker << Library >>
    component "ImagePicker" as ImagePicker << Component >>

    component "expo-location" as ExpoLocation << Library >>
    component "Location" as expoLocationComponent << Component >>

    component "expo-document-picker" as ExpoDocumentPicker << Library >>
    component "DocumentPicker" as DocumentPicker << Component >>

    component "expo-av" as ExpoAV << Library >>
    component "Audio" as AudioComponent << Component >>

    component "react-native-calendar-picker" as ReactNativeCalendarPicker << Library >>
    component "CalendarPicker" as CalendarPicker << Component >>

    control "AddEventController" as AddEventController << TS >>
    control "LocationController" as LocationController << TS >>
    control "FileController" as FileController << TS >>

    entity "EventModel" as EventModel << TS >>
    entity "LocationModel" as LocationModel << TS >>
}

' Frontend View Hierarchy
addEventView --> AddDefaultView 
addEventView --> AddDateView 
addEventView --> ChooseCategoriesView 
addEventView --> useCurrentLocation

' View Components
addEventView --> SafeAreaContext
addEventView --> ReactNative
addEventView --> ReactNativeToast
addEventView --> ReactI18next
addEventView --> ReactNavigation
addEventView --> React
addEventView --> Modal
addEventView --> AppHeader

'AddDefaultView 
AddDefaultView --> useImagePicker
AddDefaultView --> useMusicPicker
AddDefaultView --> useAudioRecorder

'AddDateView
AddDateView --> ReactNativeCalendarPicker
ReactNativeCalendarPicker --> CalendarPicker



' React
React --> useState
React --> useCallback

' Camera
useImagePicker --> ExpoCamera
ExpoCamera --> Camera

' ImagePicker
useImagePicker --> ExpoImagePicker
ExpoImagePicker --> ImagePicker

' ReactI18next
ReactI18next --> useTranslation

' DocumentPicker
useMusicPicker --> ExpoDocumentPicker
ExpoDocumentPicker --> DocumentPicker

' ExpoLocation
useCurrentLocation --> ExpoLocation
ExpoLocation --> expoLocationComponent

' Audio
useAudioRecorder --> ExpoAV
ExpoAV --> AudioComponent

' ReactNative
ReactNative --> Image
ReactNative --> Text
ReactNative --> Alert
ReactNative --> ScrollView
ReactNative --> StyleSheet

' ReactNavigation
ReactNavigation --> useNavigation
ReactNavigation --> useFocusEffect

' ReactNativeToast
ReactNativeToast --> useToast

' SafeAreaContext
SafeAreaContext --> SafeAreaView

' Controller relationships
addEventView --> AddEventController
addEventView --> LocationController
addEventView --> FileController

AddEventController --> EventModel
LocationController --> LocationModel

' User interaction
UserReg ..> addEventView


@enduml