@startuml DesignClassDiagram
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11
left to right direction
actor "Authenticated\nUser" as UserReg


package frontend <<Flutter:3.10.0>>{
    boundary "AddEventView" as addEventView << dart >>
    boundary "AddDateView" as addDateView << dart >>
    boundary "ChooseCategoriesView" as chooseCategoriesView << dart >>

    component "widgets" as widgets <<custom widgets>>
    component "material" as material <<package>>
    component "location" as locationPackage <<package>>
    component "file_picker" as flutterFilePicker <<package>>
    component "flutter_sound" as flutterSound <<package>>
    component "permission_handler" as permissionHandler <<package>>
    component "image_picker" as flutterImagePicker <<package>>

    component "Location" as location <<Class>>
    component "FilePicker" as filePicker <<Class>>
    component "FlutterSoundRecorder" as flutterSoundRecorder <<Class>>
    component "ImagePicker" as imagePicker <<Class>>

    control "EventRepository" as eventRepository << dart >>
    control "LocationRepository" as locationRepository << dart >>
    control "StorageService" as storageService << dart >>
    control "ApiClient" as apiClient << dart >>
    control "SupabaseClient" as supabaseClient << dart >>
    control "AddEventViewModel" as addEventViewModel << dart >>

    entity "EventModel" as eventModel
    entity "LocationModel" as locationModel

}

UserReg ..> addEventView

addEventView --> addDateView
addEventView --> chooseCategoriesView
addEventView --> widgets
addEventView --> material
addEventView --> locationPackage
addEventView --> flutterFilePicker
addEventView --> flutterSound
addEventView --> permissionHandler
addEventView --> flutterImagePicker
addEventView --> addEventViewModel

addEventViewModel --> eventRepository
addEventViewModel --> locationRepository
addEventViewModel --> storageService

eventRepository --> apiClient
eventRepository --> eventModel

locationRepository --> apiClient
locationRepository --> locationModel

storageService --> supabaseClient

locationPackage --> location
flutterFilePicker --> filePicker
flutterSound --> flutterSoundRecorder
flutterImagePicker --> imagePicker

@enduml