@startuml DesignClassDiagram
skinparam style strictuml
skinparam defaultTextAlignment center
skinparam defaultFontSize 11
left to right direction
actor "Authenticated\nUser" as UserReg


package frontend <<Flutter:3.10.0>>{
    boundary "AddEventView" as addEventView << Dart >>
    boundary "AddDateView" as addDateView << Dart >>
    boundary "ChooseCategoriesView" as chooseCategoriesView << Dart >>

    component "widgets" as widgets <<Custom Widgets>>
    component "material" as material <<Package>>
    component "location" as locationPackage <<Package>>
    component "file_picker" as flutterFilePicker <<Package>>
    component "flutter_sound" as flutterSound <<Package>>
    component "permission_handler" as permissionHandler <<Package>>
    component "image_picker" as flutterImagePicker <<Package>>

    component "Location" as location <<Class>>
    component "FilePicker" as filePicker <<Class>>
    component "FlutterSoundRecorder" as flutterSoundRecorder <<Class>>
    component "ImagePicker" as imagePicker <<Class>>

    control "EventRepository" as eventRepository << Dart >>
    control "LocationRepository" as locationRepository << Dart >>
    control "StorageService" as storageService << Dart >>
    control "ApiClient" as apiClient << Dart >>
    control "SupabaseClient" as supabaseClient << Dart >>
    control "AddEventViewModel" as addEventViewModel << Dart >>

    entity "EventModel" as eventModel << Dart >>
    entity "LocationModel" as locationModel << Dart >>

}

UserReg ..> addEventView

addEventView --> addDateView
addEventView --> chooseCategoriesView
addEventView --> widgets
addEventView --> material
addEventView --> locationPackage
addEventView --> flutterFilePicker
addEventView --> flutterSound
addEventView --> permissionHandler
addEventView --> flutterImagePicker
addEventView --> addEventViewModel

addEventViewModel --> eventRepository
addEventViewModel --> locationRepository
addEventViewModel --> storageService

eventRepository --> apiClient
eventRepository --> eventModel

locationRepository --> apiClient
locationRepository --> locationModel

storageService --> supabaseClient

locationPackage --> location
flutterFilePicker --> filePicker
flutterSound --> flutterSoundRecorder
flutterImagePicker --> imagePicker

@enduml