@startuml analysisColaborationDiagramUC6
object ": User" as UserReg
object ": AddEventView" as AddEventView
object ": FileController" as FileController
object ": LocationController" as LocationController
object ": AddEventController" as AddEventController
object ": EventModel" as EventModel
object ": LocationModel" as LocationModel

UserReg -r- AddEventView : handleAddEvent(event) >
AddEventView -r- FileController: > 1: uploadFile(image) 
AddEventView -r- FileController: > 2: uploadFile(music) 
AddEventView -d- LocationController: > 3: addLocation(location) 
LocationController -r- LocationModel: > 4: createLocation(location) 
AddEventView -u- AddEventController: > 5: postEvent(event) 
AddEventController -r- EventModel: > 6: createEvent(event) 

@enduml