@startuml analysisColaborationDiagramUC6
object ": User" as UserReg
object ": AddEventView" as AddEventView
object ": FileController" as FileController
object ": LocationController" as LocationController
object ": AddEventController" as AddEventController
object ": EventModel" as EventModel
object ": LocationModel" as LocationModel

UserReg -r- AddEventView : handleAddEvent(event) >
AddEventView -r- FileController: > 1: uploadFile(image) \n 2: imageUrl <
AddEventView -r- FileController: > 3: uploadFile(music) \n 4: musicUrl <
AddEventView -d- LocationController: > 5: addLocation(location) \n 8: locationId <
LocationController -r- LocationModel: > 6: createLocation(location) \n 7: location <
AddEventView -u- AddEventController: > 9: postEvent(event) \n 10: event <
AddEventController -r- EventModel: > 10: createEvent(event) \n 11: event <

@enduml