@startuml architecture_design
skinparam ComponentBackgroundColor white
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

node "Mobile Device" as mobileDevice {
    component "React Native App" as reactNativeApp <<React Native:0.76.6>> {
         component "JavaScript Layer" as jsLayer {
            component "App" as app 
            component "node_modules" as nodeModules
        }
        
        component "Bridge Layer" as bridgeLayer {
            component "React Native Bridge" as bridge
        }
        
        component "Native Layer" as nativeLayer {
            component "Native Modules" as nativeModules
            component "Native UI Components" as nativeComponents
        }

         component "React Native Runtime Environment" as runtime {
            component "Expo Runtime" as expoRuntime 
            component "JS Engine" as jsEngine
            component "Native Module Bindings" as moduleBindings
        }
        
        ' Internal connections
        jsLayer --> bridge
        bridge --> nativeLayer
        jsLayer --> runtime
        app --> nodeModules
        moduleBindings --> nativeModules
        nativeComponents --> runtime
    }

}

node "Backend" as backend {
    component "Express API" as expressAPI
    component "Prisma Client" as prismaClient
}

node "Supabase" as supabase {
    component "Authentication" as auth
    component "File Storage" as fileStorage
    component "PostgreSQL Database" as postgresDB
}

node "Expo Application Services (EAS)" as expoServices {
    component "Expo Push Notifications" as expoPushNotifications
    component "Expo Application Services Build" as expoApplicationServicesBuild
}

jsLayer <..[#000000]l..> expressAPI : <font color=000000>HTTP</font>
prismaClient <.[#000000]u.> postgresDB
jsLayer <.[#000000]d.> fileStorage
jsLayer <.[#000000]d.> auth

expressAPI <.[#000000]l.> prismaClient
jsLayer <.[#000000]d.> expoPushNotifications
jsLayer <.[#000000]d.> expoApplicationServicesBuild

@enduml