@startuml UseCaseDiagramUserManagement
    left to right direction
    actor "Usuario" as usuario
    rectangle "Eventify" {
        package "Gestión de Usuario" {
            usecase "UC23 - Ver perfil de usuario" as verPerfil
            usecase "UC24 - Editar perfil" as editarPerfil
            usecase "UC25 - Cambiar idioma" as cambiarIdioma
            usecase "UC26 - Cambiar contraseña" as cambiarContrasena
            usecase "UC27 - Ver seguidos" as verSeguidos
            usecase "UC28 - Ver seguidores" as verSeguidores
        }
    }

    usuario -- verPerfil
    usuario -- editarPerfil
    usuario -- cambiarIdioma
    usuario -- cambiarContrasena
    usuario -- verSeguidos
    usuario -- verSeguidores
@enduml