@startuml UseCaseDiagramSocialInteractions
    left to right direction
    actor "Usuario" as usuario
    rectangle "Eventify" {
        package "Interacciones Sociales" {
            usecase "UC15 - Seguir usuario" as seguirUsuario
            usecase "UC16 - Dejar de seguir usuario" as dejarSeguirUsuario
            usecase "UC17 - Ver notificaciones" as verNotificaciones
            usecase "UC18 - Buscar perfil de usuario" as buscarPerfil
            usecase "UC19 - Dar 'Me gusta' a un evento" as darMeGusta
            usecase "UC20 - Quitar 'Me gusta' a un evento" as quitarMeGusta
            usecase "UC21 - Compartir un evento" as compartirEvento
            usecase "UC22 - Comentar un evento" as comentarEvento
        }
    }

    usuario -- seguirUsuario
    usuario -- dejarSeguirUsuario   
    usuario -- verNotificaciones
    usuario -- buscarPerfil
    usuario -- darMeGusta
    usuario -- quitarMeGusta
    usuario -- compartirEvento
    usuario -- comentarEvento
@enduml