@startuml UseCaseDiagramPackages
    left to right direction
    actor "Usuario" as usuario
    rectangle "Eventify" {
        package "Autenticación"
        package "Gestión de Eventos"
        package "Interacciones Sociales"
        package "Gestión de Usuario"
    }

    usuario -- "Autenticación"
    usuario -- "Gestión de Eventos"
    usuario -- "Gestión de Usuario"
    usuario -- "Interacciones Sociales"
@enduml