@startuml UseCaseDiagramEventsManagement
    left to right direction
    actor "Usuario" as usuario
    rectangle "Eventify" {
        package "Gestión de Eventos" {
            usecase "UC5 - Buscar evento" as buscarEvento
            usecase "UC6 - Publicar evento" as publicarEvento
            usecase "UC7 - Editar evento" as editarEvento
            usecase "UC8 - Ver detalles del evento" as verDetallesEvento
            usecase "UC9 - Subir imagen al Evento" as subirImagenEvento
            usecase "UC10 - Subir música al Evento" as subirMusicaEvento
            usecase "UC11 - Agregar ubicación al Evento" as agregarUbicacionEvento
            usecase "UC12 - Editar imagen del Evento" as eliminarImagenEvento
            usecase "UC13 - Eliminar música del Evento" as editarMusicaEvento
            usecase "UC14 - Eliminar ubicación del Evento" as editarUbicacionEvento
        }
    }

    usuario -- buscarEvento
    usuario -- publicarEvento
    usuario -- editarEvento
    usuario -- verDetallesEvento
    usuario -- subirImagenEvento
    usuario -- subirMusicaEvento
    usuario -- agregarUbicacionEvento
    usuario -- eliminarImagenEvento
    usuario -- editarMusicaEvento
    usuario -- editarUbicacionEvento
@enduml